apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: products-app-prod
data:
  SPRING_PROFILES_ACTIVE: "prod"
  POSTGRES_DB: "products_prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/products_prod"
