apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: products-app

resources:
  - namespace.yml
  - postgres-pvc.yml
  - postgres-deployment.yml
  - postgres-service.yml
  - deployment.yml
  - service.yml
  - ingress.yml
